sudo: false
language: python
services:
    - postgresql
python:
    - "2.7"
    - "3.5"
    - "3.6"
env:
    - DJANGO_PACKAGE="Django==1.11" DB=sqlite
    - DJANGO_PACKAGE="Django==1.11" DB=postgres
install: pip install $DJANGO_PACKAGE markdown docutils psycopg2
before_script: psql -c 'create database test;' -U postgres
script: ./run_tests.sh
notifications:
    email:
        - james.p.turk@gmail.com
