dist: xenial
language: python
services:
    - postgresql
python:
    - "3.7"
env:
    - DJANGO_PACKAGE="Django==2.2" DB=sqlite
    - DJANGO_PACKAGE="Django==2.2" DB=postgres
install: pip install $DJANGO_PACKAGE markdown docutils psycopg2
before_script: psql -c 'create database test;' -U postgres
script: ./run_tests.sh
notifications:
    email:
        - dev@jamesturk.net
