name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
        django-version: [2.2, 3.0, 3.1]

    steps:
    # Python & dependency installation
    - uses: actions/checkout@v2
    - name: setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: pip install Django==${{ matrix.django-version }} flake8
    # - name: lint with flake8
    #   run: flake8 --show-source --statistics --ignore=E203,E501,W503
    - name: run tests
      run: django-admin.py test --settings=test_settings
      env: 
        PYTHONPATH: .
